### ISSUE TITLE
[システム系：システム] 報酬を袋にするシステム（名称未定）

### ISSUE THREAD

**Issue by Katudonsan** [TUSBAD/TUSBAD_IdeaBox#14]
### タイトル

報酬を袋にするシステム

### アイデア説明

雑貨なども含めてドロップ品の種類や数量が多くなることでインベントリがかさばるため
テラリアの「トレジャーバッグ」のように
ドロップ品は「開いたときに中身を抽選する袋」みたいなものに絞るというシステムです
袋だけにすれば
・探索時はスタックもできる
・クリアした後も必要のない袋を開けないで必要なときに開封できる
そのため、インベントリや倉庫の整頓も楽になるのではないかと考えています
そして、「袋」は使用すると決められた配分率で報酬がその場にばらまかれます

袋も２～３個落ちることあれば１個も落ちないことがある、という袋自体のドロップにランダム性を設けたり
逆にボス戦は必ず落ちる、ということもイメージしています

袋の中身イメージとしては
低確率で出てくるユニーク枠（モンスターの固有ドロップなどを含めたレアドロップ枠）や最低保証の固定枠
その中間のノーマル枠というのが基本の配分になるのではないかとイメージしています
ただし、
・ボスクラスはユニーク枠をどれか１種類出す代わりにいくつかのユニークを所持している
とか特殊な袋も考えています

ツールチップに排出する可能性のあるアイテムと排出確率を表示したり、
袋からユニーク枠が排出されたときは何かパーティクルや効果音で祝福してもいいかもしれません
・・・ここまでくるとHypixelのミステリーボックスやソシャゲのガチャみたいになってきますが

欲を言うならボス袋などの入手困難な袋はマルチプレイヤーで取り合いにならないようなシステムも欲しいです
討伐後に１人１つ自動で支給されるとか、人数に応じる、中身の数量を多くするとか？

報酬袋と併用するかどちらかにするかは分かりませんが
「報酬樽」というアイデアも提出します（内容はほとんど同じですが、こちらは設置型です・・・プレイヤーに再利用されてしまいそうですが）

あとは、モブのドロップだけでなくダンジョンや島、ディメンションの攻略報酬を袋にまとめるという案もあります
チェストに入っている報酬の中に「報酬樽」や「報酬袋」を紛れ込ませたり
エンドポータルフレームを検出して何かしら手渡すとか
先述のモブ袋は、ランダム排出を前提としましたが
島報酬などなら全固定排出もいいと思っています。

### アイデアの根拠

単純にアイテム数が多くなりすぎるとかさばるため、これを解決できれば非常に探索がしやすくなると考えているためです

**Comment by Syareene** [comment]
すっごいシステム的な話をすると
nbtが一致しない時点でアイテムのスタックが不可能になる。必ず内部的にこの袋はどのルートが出るというのを決め無いといけないため見た目は同じmobの袋でも内部的にデータが異なっているのであればスタックが不可能になる。
結果的にインベントリが埋まる(無いときよりは多少マシにはなるかもしれないけど)ので、個人的にはあまり採用したくないのかなぁと。袋を開ける手間というのも増えるからね
#15 を上手いこと改変していい感じにできれば袋に似たようなものは作れるかも

**Comment by Katudonsan** [comment]
開ける前に出るものを確定させる必要があるため
開ける瞬間に抽選することはできないんですね、分かりました
