### ISSUE TITLE
[システム系：システム] <草刈り(仮名)>

### ISSUE THREAD

**Issue by felis-alt** [TUSBAD/TUSBAD_IdeaBox#31]
### タイトル

草刈りによる素材入手のシステム追加

### アイデア説明

序盤での金稼ぎやポーションクラフト等の素材のもとになる草を刈る場所をつくる。

### アイデアの根拠

金稼ぎ方法が農業一択になっている気がするtusbであらかじめこちらが用意したフィールドで楽に稼げるかつ、クラフトシステムになれやすく、金稼ぎの役割をなくしてもなおポーション素材になり、長期的にできるコンテンツであるため。

### アイデアの効果

シングル、マルチ問わず作業の択を追加し、新しい選択肢を作る。

**Comment by felis-alt** [comment]
道具としてハサミを使用する予定。ハサミの強化等は攻略にも多少恩恵があるようにしたい。

**Comment by Syareene** [comment]
ん〜、確かにTUSBってRPGだし、**システムが用意してる土地**ってのはあっても面白いんだけど、
あくまで個人的な意見としてはTUSBって元がマインクラフトだし、農場を自分でクラフトして欲しいのよね
それを助けるためのアイテム(予め決まった農地を一定範囲に置いてくれるアイテム等)だったりとか制作素材を安くで販売するっていう解決方法も取れるし
単に金稼ぎという目的なら色んな方向からアプローチする予定なのと、作物は種類増やそうかななんて思ってる

**Comment by felis-alt** [comment]
まぁ金稼ぎって書いたのはできる選択肢増やしたいなぁってのが目的だったから…
ポーション関連も農業に取り込むなら別に却下でいいっちゃいいんだよな

**Comment by Syareene** [comment]
sbみたいに
できることは同じだけど要素が違う
(miningでいうdeep caven、dwarven mines、crystal hollows、glacite tunnelみたいな)のはあまりやりたくないから、統合で良さそうなら統合したい感はある

**Comment by felis-alt** [comment]
よきよき、個別で絶対どうこうしたいー！みたいなのはそんな無いからok

**Comment by Syareene** [comment]
んじゃあ、システムの概要がだいたい決まったあたりで農業の話も出ると思うので
その時にここで考えてたことがあったら発言してほしいかも
問題なければissue閉じます

**Comment by felis-alt** [comment]
あい
