### ISSUE TITLE
[システム系：システム] 秘伝書システム

### ISSUE THREAD

**Issue by Katudonsan** [TUSBAD/TUSBAD_IdeaBox#4]
### タイトル

秘伝書システム

### アイデア説明

スキルを使う敵から「秘伝書のページ（スキル名）」がドロップすることがある（確率はスキルにより違う）
秘伝書のページは１つのスキルに対して複数ページ存在する
全てのページを集めると「（スキル名）の秘伝書」が入手できる

（そして、作った秘伝書を使う、少なくとも何かしらの登録作業を行うことで）
例：プレイヤーはスキル設定所で秘伝書をアナザースロットにセットし「アナザースキル」として使用することができる

習得状況は共有され、覚える数の制限や一度覚えれば消滅要素などはない
ただし、アナザースキルとして使えるのは１人あたり３つまで、入れ替えは可能なので組み合わせが重要である

また、アナザースキルはオリジナルのスキルに比べて効果が弱体化している場合が多い
（これは秘伝書を読んだだけで原理も分からず使っている、いわば見よう見まねのスキルであるため）

だが、使用状況に応じて原理を理解し、運用が効率化される「チューニング」
一定以上チューニングしたスキル同士が条件下で連携し、新しいアナザースキルを追加で習得する「フュージョン」など
独自のアレンジを加えることで、オリジナルそのままでなくともオリジナルに匹敵するスキルへと昇華することができる

### アイデアの根拠

・戦闘に幅が生まれる
・職業とは違ったスキルによる新鮮な感覚
・敵のスキルを使用できるようになるという楽しさ
・アレンジによる強化・育成要素
・敵を無視せず倒すメリットが生まれる
・目標として「秘伝書の収集」が生まれる

**Comment by Syareene** [comment]
あまりにも要素が多すぎるので簡略化してほしい。
現段階ですら
- 敵のスキルをプレイヤー用にチューニングしたものを別で用意しないといけない
- 装備できるスキルには上限があり付け替え要素も実装しなければならない
- ページを集めて完成の形式のためどこのページを覚えたか、そしてどれくらい進んでいるかをプレイヤーにわかりやすく見せるUIが必要である
- チューニングについても同様で、進捗を何処かに見せたり、成長したものを別途用意する必要がある

敵のスキルを使えるというアイデア自体は面白いのでどこかで実装したいが少なくとも秘伝書という形での実装はほぼ不可能。
敵のスキルを使えるという部分はアイテム固有のスキルに敵と似たようなスキルを使えるものを用意するとかでもいいのかもしれない。

一応敵を無視せず倒すメリットが～の部分は敵から素材がドロップしたり、攻略するためにはある程度スポナー壊さないといけなかったりでその辺はある程度成約があった記憶。

**Comment by Katudonsan** [comment]
願望としては敵のスキルをそのまま、または劣化、類似したものを使えるシステムを実装したいというのがメインですので
その部分がもし採用されるのなら、その際にこのアイデアについてはバリバリに変えても問題ないです
簡略化については設定などにこだわって実装が困難になっては本末転倒
実装されるのなら、いかなる変更も構いません。むしろお願いします

**Comment by Katudonsan** [comment]
案をまとめてきました。
敵のドロップ品の中にそういう「敵のスキルが付与されたもの」が稀に落ちるというのはいかがでしょうか
毎回スキル持ちアイテムが落ちるのもあれですので
レアドロップとなるでしょうけど…
例：敵が使っていた剣に斬撃に関するスキルが備わっている
例：敵が纏っていた防具や頭に特殊な能力が備わっている
また、そこそこレアアイテムとして「使い捨てのスキルアイテム」などのアイテムも考えています

すると、雑貨なども含めてドロップ品の種類や数量が多くなることでインベントリがかさばるため
テラリアの「トレジャーバッグ」システムを参考に、ドロップ品は「開いたときに中身を抽選する袋」みたいなものを作ると
探索時はスタックもできてクリアした後も必要のない袋を開けないなら整頓も楽ではないかと考えています
モブからは武器や防具、その他ドロップ品は直接落ちず、「袋」を開封すると一定確率で入っているというものです
袋も２～３個落ちることあれば１個も落ちないことがある、という袋自体のランダム性を設けたり
逆にボス戦は必ず落ちる、というのもありですね
欲を言うならボス袋はマルチプレイヤーで取り合いにならないよう１人１つ自動で支給されたらありがたいのですが…

**Comment by Katudonsan** [comment]
袋については別Issueに建てます。
ここに付随するアイデアというより独立して建てた方がよさそうですので

**Comment by Syareene** [comment]
んーここは難しいねー
敵から落ちるのも数が多いならありだけど、敵からドロップが多すぎてもまた難しいってのが悩みどころ

**Comment by Katudonsan** [comment]
ドロップをひとまとめにしないと絶対かさばるので
不可能なイメージであると発覚しましたが、それこそ「袋」みたいな
「簡単に持ち帰れるドロップ」が欲しいなとは考えました

**Comment by Syareene** [comment]
んーこれに関しては袋のイメージに齟齬があった可能性があって
モブ固有のアイテムなどのルートを袋に対して適応させたい場合は袋は難しいけど、
共通ドロップみたいな感じで袋に対して入れるのはありだと思うんだよね
Ex: 
- 鉱石っぽい見た目をしてるモブから落ちる鉱石ブロックバンドル
- 上位モブから落ちる上位強化素材バンドル
みたいな感じのがね
そのモブ固有のドロップに対しては袋みたいなものを適応させるのは難しいかなー(そいつ限定の武器/防具を袋から確率で抽選させるみたいなの)

**Comment by Syareene** [comment]
だから固有ドロップなんかを作りたい場合はそれがそのままドロップする形になるかなぁと

**Comment by Katudonsan** [comment]
そういうことですね、分かりました！
…しかし、固有ドロップは多くなると思うので、袋以外の整理手段を考えるしかなさそうです…
ただ、少しでも共通ドロップなどは袋にまとめられたらいいですね…

**Comment by Katudonsan** [comment]
とりあえず「敵のスキルが使えるアイテムもしくはシステム」については仮採用という感じでしょうか？

**Comment by Syareene** [comment]
そうねー
どうやって組み込むかは練っていきたいね

**Comment by Katudonsan** [comment]
ありがとうございます
このシステムは巨大になると思うので、早めに案を練っておく感じでしょうかね？

**Comment by Katudonsan** [comment]
秘伝書自体は没にして、新たに「敵のスキルが使えるシステム」を別にIssue建てます
