### ISSUE TITLE
[システム系：システム] 怨魂解放

### ISSUE THREAD

**Issue by Katudonsan** [TUSBAD/TUSBAD_IdeaBox#41]
### タイトル

怨魂解放（エンコンカイホウ）

### アイデア説明

（就寝前に思いついたものを、一応他のアイデアの種になるかもと思ってメモしておきます）
構想では#40 で登場した「霊魂」のもう一つの使い道です
霊魂を何かしらの施設に使用（セット）する（同時に１つしかセットできない。入れ替えは可能だが経過時間はリセットされる）
使用すると、リアル時間１時間につき１つ、「怨魂」というアイテム（内部的にはスポーンエッグ）が精製される
※精製には１個精製しはじめると、別枠にセットした「墓場の遺品を取り返すアイテム」２個を消費する
「怨魂」はMPを消費して使用することができ、使用すると消費されてその場で「怨魂解放」が行われる
「怨魂解放」ではチャット欄に「発動する怨恨解放の名前」が流される
怨魂解放は上述の通りコストの重い消耗品だが、元になった敵をイメージした現象を一定範囲に適用することができる
※敵の「スキル」を使用するわけではない→そちらは#16 で要望中

### アイデアの根拠

おそらく採用の見込みは薄いが何か別のアイデアの種やたたき台になればいいなと考えたため

### アイデアの効果

もしそのまま実装されれば「ここぞというときの切り札」というスポットに収まるシステムになると思います

**Comment by Syareene** [comment]
なんかすっげえ複雑なシステムになるから共通システムとしての実装はできないかな
そういう効果を持つアイテムがあるとかならいいけど

**Comment by Katudonsan** [comment]
承知いたしました…
一部そういうユニークアイテムがあるくらいの、ノリですかね…？
