### ISSUE TITLE
[システム系：システム] 敬虔の祭壇

### ISSUE THREAD

**Issue by Katudonsan** [TUSBAD/TUSBAD_IdeaBox#7]
### タイトル

敬虔の祭壇（信仰システム）

### アイデア説明

TSBの信仰、マイクラの吸血鬼や狼になれる某魔術Mod
および、最近の「神のような存在と信仰や契約をして力を得る」漫画のシステムをイメージ

信仰対象（ユニークヘッドを想定する）を祭壇のチェストにセットして祈ると
加護と制約をうけることができる（片方のみの場合もある）

加護はプレイヤーに基本的に良い効果や恩寵をもたらす
制約はプレイヤーに悪い効果や制限をもたらす

信仰は１日１回、改宗できる
信仰を認めてもらうために条件を課される場合もある

### アイデアの根拠

・信仰による加護と制約を計算して活用する面白み
・信仰対象を「集める」というユニークさ
・得意な戦い方を強化することで、難易度調整の面に貢献できる

**Comment by Syareene** [comment]
もしやるならどこかの職業のクラスシステムの一部にカスティスト的な感じで入れてみるのはありだけど、
全プレイヤーが使える基礎システムとしては入れたくないかなぁ。
職業についている時点で戦い方の差別化はかなりできているから、そこに対するテコ入れはあまり入れたくない感がある。

**Comment by Katudonsan** [comment]
施設を用意したりする関係上でどうしても特定職業のために用意するにはコストが高そうですね…
「モブが落としたユニークな頭を活用した技術」を検討した末に提出したアイデアでしたが
その点が変わらない範囲で、まるっきり新しいシステムにしてもいいかもしれません。
あるいはモブのユニーク頭は素材、収集専門にするというのも検討します

**Comment by Katudonsan** [comment]
とりあえず敬虔の祭壇自体は没にします
モブのユニーク頭を活用した別の何かが思いつけばまた提出します
